additionalRepositories:
  - url: https://github.com/danieldietrich/typelevel

tasks:
  - name: typelevel setup
    init: npm i
    command: |
      npm link
      npm test
  - name: typelevel tsc
    command: |
      npm run watch
    openMode: split-right
  - name: ginject setup
    init: |
      npm link typelevel
      npm i
    command: npm test
  - name: ginject tsc
    command: |
      npm run watch
    openMode: split-right
  - name: terminal
    command: echo "Gitpod is ready!"

vscode:
  extensions:
    - dbaeumer.vscode-eslint
