additionalRepositories:
  - url: https://github.com/danieldietrich/typelevel

tasks:
  - name: typelevel setup
    init: npm i
    command: |
      npm link
      npm test
  - name: typelevel tsc
    command: |
      npm run watch
    openMode: split-right
  - name: ginject
    init: npm i
    command: npm test

vscode:
  extensions:
    - dbaeumer.vscode-eslint
