tasks:
  - before: . <(curl -sL gitprompt.sh/install)
    init: npm i
    command: npm test
    openMode: split-right

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mattpocock.ts-error-translator
